on: [push, pull_request]
name: Tests
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Install Go.
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
    - name: Checkout code.
      uses: actions/checkout@v2
    - name: Run tests.
      run: go test -v ./...
    - name: Run race detector.
      run: go test -race ./...
